server:
  port: 8082
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DBMS_CONNECTION:jdbc:mysql://mysql:3306/streaming_web}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 1000000MB
      max-request-size: 1000000MB
  sql:
    init:
      mode: always

logging:
  level:
    org:
      flywaydb:
        core: DEBUG

jwt:
  signerKey: ${SIGNER_KEY_DEV}
  valid-duration: 3600000 #second
  refreshable-duration: 12000000

cloudinary:
  cloud_name: ${CLOUD_NAME}
  api_key: ${API_KEY_CLOUDINARY}
  api_secret: ${API_SECRET_CLOUDINARY}
  secure: true
# Added Google Service Account Configuration
google:
  service-account:
    key-file: classpath:service-account-key.json

openai:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${OPENAI_API_KEY}
