server:
  port: 8082
  servlet: 
    context-path : "/api"
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/streaming_web_demo
    username: root
    password: 
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
jwt:
  signerKey : "tEKQpGumqFCmyq7bnVRym2aJWMZ0mwdJL4Q2zqtb/3hnaJ6sNXQRSXfMQsGQnFah"
  valid-duration: 20 #second
  refreshable-duration: 120 
