server:
  port: 8082
  servlet: 
    context-path : "/api"
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/streaming_web
    username: root
    password: 
  
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB

jwt:
  signerKey : "tEKQpGumqFCmyq7bnVRym2aJWMZ0mwdJL4Q2zqtb/3hnaJ6sNXQRSXfMQsGQnFah"
  valid-duration: 3600 #second
  refreshable-duration: 12000
